sudo: required
language: node_js
node_js:
  - node

after_success:
  - chmod +x deploy.sh
  - './deploy.sh'
# cache:
#   yarn: true
#   directories: node_modules

# install:
#   - npm i -g react-deploy-cli
#   - npm i
#   - npm run build

# script:
#   - rm -rf node_modules
#   - yarn build

# deploy:
#   provider: s3
#   access_key_id: '$ACCESS_KEY_ID'
#   secret_access_key: '$SECRET_ACCESS_KEY'
#   bucket: 'staging.developer.pfalfa.io'
#   skip_cleanup: true
#   acl: public_read
#   local_dir: build

# branches:
#   only:
#     - master
