language: node_js
node_js:
  - node

cache:
  yarn: true
  directories: node_modules

script:
  - rm -rf node_modules
  - yarn build

deploy:
  provider: s3
  access_key_id: '$ACCESS_KEY_ID'
  secret_access_key: '$SECRET_ACCESS_KEY'
  bucket: 'staging.developer.pfalfa.io'
  skip_cleanup: true
  acl: public_read
  local_dir: build

branches:
  only:
    - master
