# defaults: &defaults
#   docker:
#     - image: circleci/node:10

version: 2.0

jobs:
  build:
    working_directory: ~/pfalfa-dashboard-dev
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys: node-v2-{{ checksum "package.json" }}-{{ arch }}
      - run: npm install
      - save_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - build
      # - build:
      #     filters:
      #       branches:
      #         only:
      #           - master
